name: 'Image Build $(SourceBranchName) $(Date:yyyyMMdd)-$(Hours)$(Minutes)$(Seconds)'

parameters:
  - name: startEnvironment
    displayName: Environment to start from
    type: string
    default: sbx
    values:
      - sbx
      - dev
      - prd
  - name: deploymentsToPerform
    displayName: Scope of deployment
    type: string
    default: Only assets & image
    values:
      - All
      - Only removal
      - Only base
      - Only assets & image
      - Only image
  - name: osType
    displayName: OS to create the image for
    type: string
    default: Linux
    values:
      - Linux
      - Windows
  - name: waitForImageBuild
    displayName: Wait for image build
    type: boolean
    default: false
  - name: removeImageTemplateResources
    displayName: Cleanup temporal resources from previous runs
    type: boolean
    default: true

variables:
  - template: variables.yml

trigger: none

stages:
  - stage: SBX_Deployments
    displayName: Deploy to SBX
    condition: and(succeeded(), eq('${{ parameters.startEnvironment }}', 'sbx'))
    jobs:
      - template: .templates/pipeline.jobs.yml
        parameters:
          environment: 'sbx'
          osType: '${{ lower(parameters.osType) }}'
          deploymentsToPerform: '${{ parameters.deploymentsToPerform }}'
          waitForImageBuild: '${{ parameters.waitForImageBuild }}'
          removeImageTemplateResources: '${{ parameters.removeImageTemplateResources }}'

  - stage: DEV_Deployments
    displayName: Deploy to DEV
    dependsOn: SBX_Deployments
    condition: |
      and(
        in(dependencies.SBX_Deployments.result, '', 'Succeeded', 'Skipped'),
        in('${{ parameters.startEnvironment }}', 'sbx', 'dev')
      )
    jobs:
      - template: .templates/pipeline.jobs.yml
        parameters:
          environment: 'dev'
          osType: '${{ lower(parameters.osType) }}'
          deploymentsToPerform: '${{ parameters.deploymentsToPerform }}'
          waitForImageBuild: '${{ parameters.waitForImageBuild }}'
          removeImageTemplateResources: '${{ parameters.removeImageTemplateResources }}'

  - stage: PRD_Deployments
    displayName: Deploy to PRD
    dependsOn: DEV_Deployments
    condition: |
      and(
        in(dependencies.DEV_Deployments.result, '', 'Succeeded', 'Skipped'),
        or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master')),
        in('${{ parameters.startEnvironment }}', 'sbx', 'dev', 'prd')
      )
    jobs:
      - template: .templates/pipeline.jobs.yml
        parameters:
          environment: 'prd'
          osType: '${{ lower(parameters.osType) }}'
          deploymentsToPerform: '${{ parameters.deploymentsToPerform }}'
          waitForImageBuild: '${{ parameters.waitForImageBuild }}'
          removeImageTemplateResources: '${{ parameters.removeImageTemplateResources }}'
